---
- name: 1 update system
  apt: update_cache=yes upgrade=dist cache_valid_time=3600

- name: 2 install Apache
  apt: name=apache2 state=present

- name: 3 install PHP
  apt: "name={{ item }} state=present"
  with_items:
    - php
    - php-gd
    - php-mcrypt
    - libapache2-mod-php
    - libmysqlclient-dev

- name: 4 install MySQL
  apt: "name={{ item }} state=present"
  with_items: 
    - mysql-common
    - php-mysql
    - mysql-server
    - python-mysqldb

- name: 5 Start Apache, MySQL an PHP
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - apache2
    - mysql

- name: 6 Enable Apache rewrite module
  apache2_module: name=rewrite state=present
  notify: restart apache2

#- name: 7 Remove test MySQL DB
#  mysql_db: db=test state=absent

- name: 8 install composer and set global
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755

- name: 9 run composer instaler file
  command: >
    php composer-installer.php
    chdir=/tmp
    creates=/usr/local/bin/composer

- name: 10 copy composer file for global use
  shell: >
    mv /tmp/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer	

- name: 11 install NodeJs and npm
  apt: "name={{ item }} state=present"
  with_items:
    - nodejs
    - npm
